language: objective-c
osx_image: xcode7
xcode_project: Framework/YYModel.xcodeproj
xcode_scheme: YYModel
script:
- xcodebuild -project Framework/YYModel.xcodeproj -scheme YYModel test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES